services:
  - type: web
    name: maxx-stream
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node src/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: 18
      - key: BREVO_API_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        value: suportemaxxstream@gmail.com
      - key: EMAIL_FROM_NAME
        value: MAXX STREAM
      - key: SEVENTV_API_KEY
        sync: false
      - key: SEVENTV_PARTNER_ID
        sync: false
      - key: ADMIN_QUICK_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        value: '*'
    healthCheckPath: /api/health
    autoDeploy: true